version: '3.7'

services:
  app:
    image: tmshv/jupyter:2.2
    container_name: jupyter
    restart: always
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - ./data:/data
    ports:
      - "127.0.0.1:8888:8888"

